### ISSUE TITLE
Tom's Simple Storage wipes inventory of Crates

### ISSUE THREAD

**Issue by SimonMeskens** [Khazoda/basic-storage#4]
I have several crates connected to an Inventory Connector from Tom's Storage, with a crafting terminal connected to the Connector. When I craft anything, it wipes all connected Crates.

1.20.1 with Basic Storage 1.0.3

**Comment by khazoda** [comment]
Thanks for the bug report, I'll look into this

**Comment by khazoda** [comment]
Thanks for reporting this pretty critical bug @SimonMeskens, please try 1.0.4+1.20.1 sometime and let me know if your issue still persists.

**Comment by SimonMeskens** [comment]
Seems to work!
